### ISSUE TITLE
schema

### ISSUE THREAD

**Issue by easchwar** [twosatnams/catchup#1]
friendships - be careful with how you implement friendships. They can be tricky since there are 3 "states" of friendships--friends, not friends, pending. The "pending" attribute is a good solution here.

**Comment by twosatnams** [comment]
I'm planning on doing this like -
1. User A sends User B a friend request, following entry is created in the friends table - 
   
   [id, UserA_id, UserB_id, false]
   - User A will be able to see his unsuccessful requests using:-
     
     SELECT friend_id FROM friends WHERE user_id = userA_id AND pending = true;
   - User B will be able to see friend requests sent to him using - 
     
     SELECT user_id FROM friends WHERE friend_id = UserB_id AND pending = false;
2. If User B accepts the friend request, then the pending attribute of the friend request will be updated to true. The tricky part for me is how do I get all of the friends for a particular user. I'm currently contemplating a self-join on friends table or maybe polishining the following query to return only the friends of the user -
   
   SELECT \* FROM friends WHERE user_id = user.id OR friend_id = user.id AND pending = false;
