### ISSUE TITLE
user images

### ISSUE THREAD

**Issue by easchwar** [twosatnams/catchup#4]
Photos are one of the most integral components of facebook. I would suggest adding photos as part of your MVP.

**Comment by easchwar** [comment]
this should take the form of both a profile photo and photo collections

**Comment by twosatnams** [comment]
Sure! I can include photos. The way I'm thinking of inlcuding them is using posts (phase 2) - 
- When creating a post, a user can include (optional) one or multiple pictures.
- User can also view pictures of himself and other users by going to a photos link on the profile page.

I'll update the details of the proposal including the wireframes soon.
